/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicagrupal1;

/**
 *
 * @author and_j
 */
public class InterfazEvento extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEvento
     */
    public InterfazEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        lblIngresePart = new javax.swing.JLabel();
        btnRegistar = new javax.swing.JButton();
        cmbxParticipante = new javax.swing.JComboBox<>();
        lblEvento = new javax.swing.JLabel();
        ckcTransporte = new javax.swing.JCheckBox();
        ckcAlmuerzo = new javax.swing.JCheckBox();
        ckcMaterialApoyo = new javax.swing.JCheckBox();
        btnMorning = new javax.swing.JRadioButton();
        btnTarde = new javax.swing.JRadioButton();
        lblHorario = new javax.swing.JLabel();
        lblEscojaCategoria = new javax.swing.JLabel();
        lblServicios = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMostrarDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.setColumns(20);
        txtNombre.setRows(5);
        jScrollPane1.setViewportView(txtNombre);

        lblIngresePart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblIngresePart.setText("Ingrese Nombre:");

        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        cmbxParticipante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Participante", "Invitado Especial" }));

        lblEvento.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        lblEvento.setText("Registro de Evento");

        ckcTransporte.setText("Transporte");

        ckcAlmuerzo.setText("Almuerzo");
        ckcAlmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckcAlmuerzoActionPerformed(evt);
            }
        });

        ckcMaterialApoyo.setText("Material de Apoyo");

        buttonGroup1.add(btnMorning);
        btnMorning.setText("Matutino");

        buttonGroup1.add(btnTarde);
        btnTarde.setText("Vespertino");

        lblHorario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHorario.setText("Horario");

        lblEscojaCategoria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEscojaCategoria.setText("Escoja Categoria");

        lblServicios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblServicios.setText("Servicios Requeridos");

        btnMostrar.setText("Historial");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        txtAMostrarDatos.setColumns(20);
        txtAMostrarDatos.setRows(5);
        jScrollPane2.setViewportView(txtAMostrarDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckcMaterialApoyo)
                            .addComponent(ckcTransporte)
                            .addComponent(ckcAlmuerzo)
                            .addComponent(cmbxParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServicios)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMorning)
                                .addGap(86, 86, 86)
                                .addComponent(btnTarde)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblEscojaCategoria)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEvento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(lblHorario))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIngresePart)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnRegistar)
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblIngresePart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEscojaCategoria)
                .addGap(8, 8, 8)
                .addComponent(cmbxParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblServicios)
                .addGap(14, 14, 14)
                .addComponent(ckcAlmuerzo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckcTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckcMaterialApoyo)
                .addGap(18, 18, 18)
                .addComponent(lblHorario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMorning)
                            .addComponent(btnTarde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistar)
                            .addComponent(btnMostrar))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckcAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckcAlmuerzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckcAlmuerzoActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
    String Participant=txtNombre.getName();
    String Categorias= (String)cmbxParticipante.getSelectedItem();
    String Almuerzo= Boolean.toString(ckcAlmuerzo.isSelected());
    String Transporte=Boolean.toString(ckcTransporte.isSelected());
    String MaterialDeApoyo=Boolean.toString(ckcMaterialApoyo.isSelected());
  
    boolean Tarde=(btnTarde.isSelected());
    boolean Morning= btnMorning.isSelected();
    
    
    if(Morning){
      turno="Mañana"

    }else if(Tarde){
            turno="Tarde";
       }
    
    String [] datosUsuario= new String[6];
    datosUsuario[0]=Participant;
    datosUsuario[1]=Categorias;
    datosUsuario[2]=Almuerzo;
    datosUsuario[3]=Transporte;
    datosUsuario[4]=MaterialDeApoyo;
    datosUsuario[5]= Tarde;
    datosUsuario[6]= Morning;
    
    }
    
    //DOmenica
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
     String datos="";
     for (int i = 0;i<6; i++){
         System.out.println("Datos"+datosUsuario[i]);
          datos=datos+","+datosUsuarios[i];
     }
    txtAMostrarDatos.setText(datos);
     
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnMorning;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JRadioButton btnTarde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckcAlmuerzo;
    private javax.swing.JCheckBox ckcMaterialApoyo;
    private javax.swing.JCheckBox ckcTransporte;
    private javax.swing.JComboBox<String> cmbxParticipante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEscojaCategoria;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblIngresePart;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JTextArea txtAMostrarDatos;
    private javax.swing.JTextArea txtNombre;
    // End of variables declaration//GEN-END:variables
}
